Adecuamos migasfree-tags haciendo uso de flock

diff --git a/usr/bin/vx-migasfree-tags-save-tmp b/usr/bin/vx-migasfree-tags-save-tmp
--- a/usr/bin/vx-migasfree-tags-save-tmp
+++ b/usr/bin/vx-migasfree-tags-save-tmp
@@ -3,11 +3,15 @@
 FICHFUCS="/usr/bin/vx-funcs-bash"
 [ -f "${FICHFUCS}" ] && . "${FICHFUCS}"
 
-vx-check_user_root
+EJECUTOR="$(whoami)"
+[ "${EJECUTOR}" != "root" ] && \
+echo "=> ¡¡Error!! Debes ser root para gestionar las etiquetas migasfree" && \
+exit 1
 
 FICH="/tmp/migasfree.tags"
 if [[ "${1}" == "-g" ]] ; then
-    if ETIQUETAS="$(migasfree-tags --save-tmp)" ; then
+    [ -f "${FICH}" ] && rm -f "${FICH}"
+    if ETIQUETAS="$(migasfree-tags -g)" ; then
         echo "${FICH}: $(cat ${FICH})"
     fi
 else
diff --git a/usr/share/divert/usr/bin/migasfree-tags b/usr/share/divert/usr/bin/migasfree-tags
--- a/usr/share/divert/usr/bin/migasfree-tags
+++ b/usr/share/divert/usr/bin/migasfree-tags
@@ -3,24 +3,28 @@
 ORIGINAL="migasfree-tags.orig"
 FICHLOCK="/tmp/migasfree.tags.lock"
 FICHTAGS="/tmp/migasfree.tags"
+TIMELOCK="15"
 
 [ "$(whoami)" != "root" ] && \
 echo "=> Necesitas ser root para hacer uso de migasfree-tags" && \
 exit 1
 
-CONT=0
-while [[ -f "${FICHLOCK}" ]] && (( CONT < 300 )) ; do
-    sleep 1
-    (( CONT++ ))
-done
-(( CONT == 300 )) && \
-echo "=> Hay un problema de conexión al tratar de obtener las etiquetas" && \
-exit 2
+function desbloquear() {
+    flock -u "$lock_fd"
+}
 
-touch "${FICHLOCK}"
+function bloquear() {
+    # Como primer parametro pasammos el modo de bloqueo, lectura (-s) o escritura (-w):
+    # Creamos un descriptor que nos permitirá escribir sobre el archivo bloqueado:
+    exec {lock_fd}>"${FICHLOCK}" || exit 1
+    flock -w "${TIMELOCK}" "$lock_fd" || \
+    {
+        echo "=> ERROR: migasfree-tags flock() ha fallado" >&2;
+        exit 1;
+    }
+}
 
 function salir() {
-    rm "${FICHLOCK}"
     exit ${1}
 }
 
@@ -34,6 +38,7 @@ function get_tags() {
             if ETIQUETAS="$("${ORIGINAL}" -g)" ; then
                 EXITO=1
                 echo -n "${ETIQUETAS}" | sed 's/"//g' > "${FICHTAGS}"
+                # echo -n "${ETIQUETAS}" | sed 's/"//g' 1>&$lock_fd
             fi
             sleep 5
             ((CONT++))
@@ -44,10 +49,9 @@ function get_tags() {
     fi
     [ -f "${FICHTAGS}" ] && ETIQUETAS="$(sed 's/"//g' "${FICHTAGS}")" || salir "1"
     "${SALIDA}" && echo "${ETIQUETAS}"
-    salir "0"
 }
 
-
+bloquear
 
 # Comprobamos si el primer parámetro quiere obtener las etiquetas
 if [[ "${1}" =~ ^-g$|^--get$ ]] ; then
@@ -56,16 +60,26 @@ fi
 
 # Comprobamos si el primer parámetro quiere obtener las etiquetas
 if [[ "${1}" =~ ^--save-tmp$ ]] ; then
+    [ -f "${FICHTAGS}" ] && rm "${FICHTAGS}"
     get_tags "false"
 fi
 
-# Comprobamos si se quiere reetiquetar al equipo
-if [[ "${1}" =~ ^-c$|^--communicate$|^-s$|^--set$ ]] ; then
-    if "${ORIGINAL}" "${@}" ; then
-        rm "${FICHTAGS}"
+function sincronizar_tags() {
+    if "${ORIGINAL}" -c "${@}" ; then
+        [ -f "${FICHTAGS}" ] && rm "${FICHTAGS}"
         get_tags "false"
     fi
-    salir "1"
+}
+
+# Comprobamos si se quiere reetiquetar al equipo
+if [[ "${1}" =~ ^-c$|^--communicate$ ]] ; then
+    shift && sincronizar_tags "${@}"
+fi
+
+if [[ "${1}" =~ ^-s$|^--set$ ]] ; then
+    shift && sincronizar_tags "${@}"
+    desbloquear
+    migasfree --update --force-upgrade
 fi
 
 if [[ "${1}" =~ ^-a$|^--available$ ]] ; then
@@ -77,3 +91,5 @@ if [[ -z "${1}" ]] ; then
     "${ORIGINAL}"
     salir "2"
 fi
+
+salir "0"
