Divertimos el migasfree-tags para evitar conflictos de concurrencia en su llamada

diff --git a/usr/bin/vx-migasfree-tags-save-tmp b/usr/bin/vx-migasfree-tags-save-tmp
--- a/usr/bin/vx-migasfree-tags-save-tmp
+++ b/usr/bin/vx-migasfree-tags-save-tmp
@@ -3,19 +3,19 @@
 FICHFUCS="/usr/bin/vx-funcs-bash"
 [ -f "${FICHFUCS}" ] && . "${FICHFUCS}"
 
-vx-check_user_root
+EJECUTOR="$(whoami)"
+[ "${EJECUTOR}" != "root" ] && \
+echo "=> ¡¡Error!! Debes ser root para gestionar las etiquetas migasfree" && \
+exit 1
 
-# Fichero donde se guardan temporalmente las tags:
 FICH="/tmp/migasfree.tags"
-
-if ! [ -z "${1}" ] ; then
-    echo -n "${@}" > "${FICH}" && \
-    echo "=> Ok!! Etiquetas Guardadas en ${FICH}" || \
-    echo "=> Error!! No se han podido guardar las etiquetas en ${FICH}"
-else
-    if ETIQUETAS=$(sudo migasfree-tags -g 2> /dev/null) ; then
-        echo "${ETIQUETAS}" > /tmp/migasfree.tags
-        chmod 644 /tmp/migasfree.tags
+if [[ "${1}" == "-g" ]] ; then
+    [ -f "${FICH}" ] && rm -f "${FICH}"
+    if ETIQUETAS="$(migasfree-tags -g)" ; then
+        echo "${FICH}: $(cat ${FICH})"
     fi
+else
+    echo -n "${@}" > "${FICH}" && \
+    echo "=> Ok!! Etiquetas Guardadas en ${FICH}: ${@}" || \
+    echo "=> Error!! No se han podido guardar las etiquetas en ${FICH}"
 fi
-
